// ISO 3166-1 alpha-2 → Portuguese country names
// Complete list for radio analytics geographic distribution
export const countryNames: Record<string, string> = {
  AF: 'Afeganistão',
  AL: 'Albânia',
  DZ: 'Argélia',
  AD: 'Andorra',
  AO: 'Angola',
  AG: 'Antígua e Barbuda',
  AR: 'Argentina',
  AM: 'Arménia',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BS: 'Bahamas',
  BH: 'Barém',
  BD: 'Bangladeche',
  BB: 'Barbados',
  BY: 'Bielorrússia',
  BE: 'Bélgica',
  BZ: 'Belize',
  BJ: 'Benim',
  BT: 'Butão',
  BO: 'Bolívia',
  BA: 'Bósnia e Herzegovina',
  BW: 'Botsuana',
  BR: 'Brasil',
  BN: 'Brunei',
  BG: 'Bulgária',
  BF: 'Burquina Fasso',
  BI: 'Burúndi',
  CV: 'Cabo Verde',
  KH: 'Camboja',
  CM: 'Camarões',
  CA: 'Canadá',
  CF: 'República Centro-Africana',
  TD: 'Chade',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colômbia',
  KM: 'Comores',
  CG: 'Congo',
  CD: 'Rep. Dem. do Congo',
  CR: 'Costa Rica',
  CI: 'Costa do Marfim',
  HR: 'Croácia',
  CU: 'Cuba',
  CY: 'Chipre',
  CZ: 'Chéquia',
  DK: 'Dinamarca',
  DJ: 'Jibuti',
  DM: 'Dominica',
  DO: 'República Dominicana',
  EC: 'Equador',
  EG: 'Egito',
  SV: 'El Salvador',
  GQ: 'Guiné Equatorial',
  ER: 'Eritreia',
  EE: 'Estónia',
  SZ: 'Eswatini',
  ET: 'Etiópia',
  FI: 'Finlândia',
  FJ: 'Fiji',
  FR: 'França',
  GA: 'Gabão',
  GM: 'Gâmbia',
  GE: 'Geórgia',
  DE: 'Alemanha',
  GH: 'Gana',
  GR: 'Grécia',
  GD: 'Granada',
  GT: 'Guatemala',
  GN: 'Guiné',
  GW: 'Guiné-Bissau',
  GY: 'Guiana',
  HT: 'Haiti',
  HN: 'Honduras',
  HU: 'Hungria',
  IS: 'Islândia',
  IN: 'Índia',
  ID: 'Indonésia',
  IR: 'Irão',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IL: 'Israel',
  IT: 'Itália',
  JM: 'Jamaica',
  JP: 'Japão',
  JO: 'Jordânia',
  KZ: 'Cazaquistão',
  KE: 'Quénia',
  KI: 'Quiribáti',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  KG: 'Quirguistão',
  LA: 'Laos',
  LV: 'Letónia',
  LB: 'Líbano',
  LS: 'Lesoto',
  LR: 'Libéria',
  LY: 'Líbia',
  LI: 'Listenstaine',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MG: 'Madagáscar',
  MW: 'Maláui',
  MY: 'Malásia',
  MV: 'Maldivas',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Ilhas Marshall',
  MR: 'Mauritânia',
  MU: 'Maurícia',
  MX: 'México',
  FM: 'Micronésia',
  MD: 'Moldávia',
  MC: 'Mónaco',
  MN: 'Mongólia',
  ME: 'Montenegro',
  MA: 'Marrocos',
  MZ: 'Moçambique',
  MM: 'Mianmar',
  NA: 'Namíbia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Países Baixos',
  NZ: 'Nova Zelândia',
  NI: 'Nicarágua',
  NE: 'Níger',
  NG: 'Nigéria',
  MK: 'Macedónia do Norte',
  NO: 'Noruega',
  OM: 'Omã',
  PK: 'Paquistão',
  PW: 'Palau',
  PS: 'Palestina',
  PA: 'Panamá',
  PG: 'Papua Nova Guiné',
  PY: 'Paraguai',
  PE: 'Peru',
  PH: 'Filipinas',
  PL: 'Polónia',
  PT: 'Portugal',
  QA: 'Catar',
  RO: 'Roménia',
  RU: 'Rússia',
  RW: 'Ruanda',
  KN: 'São Cristóvão e Neves',
  LC: 'Santa Lúcia',
  VC: 'São Vicente e Granadinas',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'São Tomé e Príncipe',
  SA: 'Arábia Saudita',
  SN: 'Senegal',
  RS: 'Sérvia',
  SC: 'Seicheles',
  SL: 'Serra Leoa',
  SG: 'Singapura',
  SK: 'Eslováquia',
  SI: 'Eslovénia',
  SB: 'Ilhas Salomão',
  SO: 'Somália',
  ZA: 'África do Sul',
  SS: 'Sudão do Sul',
  ES: 'Espanha',
  LK: 'Sri Lanca',
  SD: 'Sudão',
  SR: 'Suriname',
  SE: 'Suécia',
  CH: 'Suíça',
  SY: 'Síria',
  TW: 'Taiwan',
  TJ: 'Tajiquistão',
  TZ: 'Tanzânia',
  TH: 'Tailândia',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TO: 'Tonga',
  TT: 'Trindade e Tobago',
  TN: 'Tunísia',
  TR: 'Turquia',
  TM: 'Turquemenistão',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ucrânia',
  AE: 'Emirados Árabes Unidos',
  GB: 'Reino Unido',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VU: 'Vanuatu',
  VA: 'Vaticano',
  VE: 'Venezuela',
  VN: 'Vietname',
  YE: 'Iémen',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue',
  // Territórios relevantes
  HK: 'Hong Kong',
  MO: 'Macau',
  PR: 'Porto Rico',
  GF: 'Guiana Francesa',
  GP: 'Guadalupe',
  MQ: 'Martinica',
  RE: 'Reunião',
  Unknown: 'Desconhecido',
};

export function getCountryName(code: string): string {
  return countryNames[code] || code;
}
